"""remove unique from phone and national code

Revision ID: 16a6ad8f3d6e
Revises: 0faa859cb44b
Create Date: 2026-08-08 20:35:49.770484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a6ad8f3d6e'
down_revision = '0faa859cb44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('national_code'))
        batch_op.drop_index(batch_op.f('phone'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('national_code'), ['national_code'], unique=True)

    # ### end Alembic commands ###
