"""fullname table is remove

Revision ID: cdcb1de41478
Revises: 16a6ad8f3d6e
Create Date: 2026-08-08 21:23:45.553938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdcb1de41478'
down_revision = '16a6ad8f3d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
