"""tables update

Revision ID: eb37c16a00c6
Revises: c9525f8dcbe0
Create Date: 2026-08-10 21:40:41.768899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb37c16a00c6'
down_revision = 'c9525f8dcbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('appointment_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_date', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
